# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGNjM2JiNTQ5NDE0OWMwZDU1NDc3MGQzZjFhYTI1ZjgxMTRiZThiZmJiMTE2MzQzNWQ0MzI5YTI0YzVjMTk0ZTJmYWZhZTNjMzlhZWNkZGY4ODUwYmM5MTVlYWQ4MWJmYzQwMGNlZDFiNTQ4ZDBhMjFiYTVmZDNhMjJhOTExOTc=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
